# Generated by Django 4.0.6 on 2022-11-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='urun',
        ),
    ]
