# Generated by Django 4.0.6 on 2022-11-17 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_rename_product_comment_urun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='urun',
            new_name='product',
        ),
    ]
