# Generated by Django 4.0.6 on 2022-11-25 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0032_remove_comment_user_comment_comment_writer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_writer',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='yazan', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
