# Generated by Django 4.0.6 on 2022-11-25 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0033_remove_comment_comment_writer_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_write',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='comment_write', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
