# Generated by Django 4.0.6 on 2022-12-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_alter_comment_product_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'Bekliyot'), ('True', 'Onaylandı'), ('False', 'Reddedildi')], default='New', max_length=10),
        ),
    ]
