# Generated by Django 4.0.6 on 2022-12-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_product_discounted_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'Bekliyor'), ('True', 'Onaylandı'), ('False', 'Reddedildi')], default='New', max_length=10),
        ),
    ]
