# Generated by Django 4.0.6 on 2022-11-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('product', '0027_alter_comment_user'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('home', '0004_remove_setting_profile_customusermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUserModel',
            new_name='UserModel',
        ),
    ]
