# Generated by Django 4.0.6 on 2022-11-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customusermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
        migrations.DeleteModel(
            name='CustomUserModel',
        ),
    ]
