# Generated by Django 4.0.6 on 2022-11-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_setting_avatar_delete_customusermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='avatar',
        ),
        migrations.AddField(
            model_name='setting',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
