# Generated by Django 4.0.6 on 2022-11-25 09:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0010_remove_setting_profile_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserProfileModel',
        ),
        migrations.AlterModelOptions(
            name='userprofilemodel',
            options={'verbose_name': 'Kullanıcı', 'verbose_name_plural': 'Kullanıcılar'},
        ),
        migrations.AlterModelTable(
            name='userprofilemodel',
            table='Kullanıcı',
        ),
    ]
