# Generated by Django 4.0.6 on 2022-11-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_userprofile_userprofilemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='username',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
