# Generated by Django 4.0.6 on 2022-11-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_userprofilemodel_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileModel',
        ),
    ]
