# Generated by Django 4.0.6 on 2022-11-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
