# Generated by Django 4.0.6 on 2022-12-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FaQ',
        ),
    ]
