# Generated by Django 4.0.6 on 2022-11-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcart',
            options={'verbose_name': 'Sepete_ekle', 'verbose_name_plural': 'Sepete_ekle'},
        ),
        migrations.AlterModelTable(
            name='shopcart',
            table='Sepete_ekle',
        ),
    ]
