# Generated by Django 4.0.6 on 2022-11-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_oderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adminnote',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
