# Generated by Django 4.0.6 on 2022-12-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_rename_adminnote_order_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
    ]
