# Generated by Django 4.0.6 on 2022-12-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shopcart',
            field=models.ManyToManyField(blank=True, to='order.shopcart'),
        ),
    ]
