# Generated by Django 4.0.6 on 2022-12-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_shopcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_it_paid',
            field=models.BooleanField(default=False),
        ),
    ]
