# Generated by Django 4.0.6 on 2022-12-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_is_it_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OderProduct',
        ),
    ]
