# Generated by Django 4.0.6 on 2022-12-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_delete_oderproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
