# Generated by Django 4.0.6 on 2022-12-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Sipariş', 'verbose_name_plural': 'Siparişler'},
        ),
        migrations.AlterModelTable(
            name='order',
            table='Siparişler',
        ),
    ]
