# Generated by Django 4.0.6 on 2022-12-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_remove_order_product_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Is_it_paid',
            field=models.BooleanField(default=False),
        ),
    ]
