# Generated by Django 4.0.6 on 2022-12-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Is_it_paid',
            new_name='is_it_paid',
        ),
    ]
