# Generated by Django 4.0.6 on 2022-12-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_rename_is_it_paid_order_is_it_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ManyToManyField(to='order.shopcart'),
        ),
    ]
