# Generated by Django 4.0.6 on 2022-12-09 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_alter_comment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0025_rename_total_order_total_price_shopcart_is_it_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cargo',
            new_name='adminnote',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='create_att',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_at',
            new_name='update_att',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_it_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='is_it_paid',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(default=1, editable=False, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Yeni'), ('Accepted', 'Kabul Edildi'), ('Preaparing', 'Hazırlanıyor'), ('OnShihipping', 'Kargoda'), ('Complated', 'Tamamlanmış'), ('Canceled', 'İptal Edildi')], default='New', max_length=12),
        ),
        migrations.CreateModel(
            name='OderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('New', 'Yeni'), ('Accepted', 'Kabul Edildi'), ('Canceled', 'İptal Edildi')], default='New', max_length=12)),
                ('create_att', models.DateTimeField(auto_now_add=True)),
                ('update_att', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
